env:
  CODECOV_TOKEN: ENCRYPTED[0bad38cf59a2fda73e72491e18a564995cf3a5c862b5400834bfa9873713e780a2deed3e57b265279bd1e91168ee492a]

unit_test_task:
  container:
    image: cirrusci/flutter
  test_script: COVERAGE=1 ./tool/test.sh
  codecov_script: bash <(curl -s https://codecov.io/bash)

ios_test_task:
  osx_instance:
    image: mojave-xcode-10.2-flutter
  setup_script:
    xcrun simctl create iPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-12-2 | xargs xcrun simctl boot
  test_script: ./tool/integration.sh

android_test_task:
  container:
    image: cirrusci/flutter
  env:
    EMULATOR_API_LEVEL: 22
    ANDROID_ABI: "default;armeabi-v7a"
  pin_emulator_script:
    - ${ANDROID_HOME}/emulator/emulator -version
    - emulator_version=5264690
    - curl -fo emulator.zip "https://dl.google.com/android/repository/emulator-linux-$emulator_version.zip"
    - rm -rf "${ANDROID_HOME}/emulator"
    - unzip -q emulator.zip -d "${ANDROID_HOME}"
    - ${ANDROID_HOME}/emulator/emulator -version
  install_images_script: sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  create_device_script:
    echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window
  wait_for_emulator_script:
    android-wait-for-emulator
  test_script: ./tool/integration.sh
